/**
 * Virginia localities (alphabetized) for Benefits Cliff Calculator.
 */
const LOCALITIES = [
  "Accomack",
  "Albemarle",
  "Alexandria City",
  "Alleghany",
  "Amelia",
  "Amherst",
  "Appomattox",
  "Arlington County",
  "Augusta",
  "Bath",
  "Bedford",
  "Bland",
  "Botetourt",
  "Bristol",
  "Brunswick",
  "Buchanan",
  "Buckingham",
  "Buena Vista",
  "Campbell",
  "Caroline",
  "Carroll",
  "Charles City",
  "Charlotte",
  "Charlottesville City",
  "Chesapeake",
  "Chesterfield",
  "Clarke",
  "Colonial Heights",
  "Covington",
  "Craig",
  "Culpeper",
  "Cumberland",
  "Danville city",
  "Dickenson County",
  "Dinwiddie",
  "Emporia",
  "Essex",
  "Fairfax City",
  "Fairfax county",
  "Falls Church City",
  "Fauquier",
  "Floyd",
  "Fluvanna",
  "Franklin city",
  "Franklin County",
  "Frederick",
  "Fredericksburg City",
  "Galax City",
  "Giles",
  "Gloucester",
  "Goochland",
  "Grayson",
  "Greene",
  "Greensville",
  "Halifax",
  "Hampton City",
  "Hanover",
  "Harrisonburg City",
  "Henrico",
  "Henry",
  "Highland",
  "Hopewell City",
  "Isle Of Wight",
  "James City",
  "King And Queen",
  "King George",
  "King William",
  "Lancaster",
  "Lee",
  "Lexington City",
  "Loudoun",
  "Louisa",
  "Lunenburg",
  "Lynchburg City",
  "Madison",
  "Manassas City",
  "Manassas Park City",
  "Martinsville City",
  "Mathews",
  "Mecklenburg",
  "Middlesex",
  "Montgomery",
  "Nelson",
  "New Kent",
  "Newport News",
  "Norfolk",
  "Northampton",
  "Northumberland",
  "Norton City",
  "Nottoway",
  "Orange",
  "Page",
  "Patrick",
  "Petersburg City",
  "Pittsylvania",
  "Poquoson City",
  "Portsmouth City",
  "Powhatan",
  "Prince Edward",
  "Prince George",
  "Prince William",
  "Pulaski",
  "Radford City",
  "Rappahannock",
  "Richmond City",
  "Richmond County",
  "Roanoke City",
  "Roanoke County",
  "Rockbridge-Buena Vista-Lexington",
  "Rockingham",
  "Russell",
  "Salem City",
  "Scott",
  "Shenandoah",
  "Smyth",
  "Southampton",
  "Spotsylvania",
  "Stafford",
  "Staunton City",
  "Suffolk",
  "Surry",
  "Sussex",
  "Tazewell",
  "Virginia Beach City",
  "Warren",
  "Washington",
  "Waynesboro City",
  "Westmoreland",
  "Williamsburg City",
  "Winchester City",
  "Wise",
  "Wythe",
  "York",
];

/** Benefit program definitions: id used in DOM, label shown to user. */
const BENEFIT_PROGRAMS = [
  { id: "child_care_subsidy", label: "Child Care Subsidy" },
  { id: "eitc", label: "EITC" },
  { id: "marketplace", label: "Health Insurance Marketplace Subsidies" },
  { id: "hcv", label: "Housing Choice Voucher" },
  { id: "medicaid", label: "Medicaid" },
  { id: "snap", label: "SNAP" },
  { id: "tanf", label: "TANF" },
  { id: "tanf_view", label: "TANF/VIEW" },
  { id: "wic", label: "WIC" },
];

/** Child age band options: value stored, label shown. */
const CHILD_AGE_BANDS = [
  { value: "infant", label: "Infant (16 months or younger)" },
  { value: "toddler", label: "Toddler (16–23 months)" },
  { value: "two", label: "Two year old (24–36 months)" },
  { value: "preschool", label: "Preschool (36 months to 5 years, not yet in kindergarten)" },
  { value: "school_age", label: "School age (eligible for public school, under 13 years)" },
  { value: "teen_capable", label: "13 years or older (capable of caring for themselves)" },
  { value: "teen_incapable", label: "13–18 (physically or mentally incapable of self-care)" },
];
